# =============================================
# Application Configuration for Generic MCP Server
# ---------------------------------------------
# - name: Application name for Spring context
# - banner-mode: Disables Spring Boot startup banner
# - log-startup-info: Suppresses startup info logs
# - ai.mcp.server.enabled: Enables MCP server (stdio transport)
# - ai.mcp.server.capabilities: Enables tools/resources/prompts
# - logging.level: Sets log levels for app, MCP, Spring AI, and root
# =============================================

spring:
  application:
    name: generic-mcp-server
  main:
    banner-mode: off
    log-startup-info: false
  ai:
    mcp:
      server:
        enabled: true
        # Stdio transport only for Claude Desktop compatibility
        capabilities:
          tools: true
          resources: true
          prompts: true

logging:
  level:
    com.example.genericmcp: DEBUG
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai: DEBUG
    root: WARN