# =============================================
# Application Configuration for Generic MCP Server
# ---------------------------------------------
# - name: Application name for Spring context
# - banner-mode: Disables Spring Boot startup banner
# - log-startup-info: Suppresses startup info logs
# - ai.mcp.server.enabled: Enables MCP server (stdio transport)
# - ai.mcp.server.stdio: Enables stdio transport for Claude Desktop
# - ai.mcp.server.capabilities: Enables tools/resources/prompts
# - server.port: Web server port for SSE transport
# - logging.level: Sets log levels for app, MCP, Spring AI, and root
# =============================================

spring:
  application:
    name: generic-mcp-server
  main:
    banner-mode: off
    log-startup-info: false
  ai:
    mcp:
      server:
        enabled: true
        stdio: true  # Enable stdio transport for Claude Desktop
        name: generic-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "Generic MCP server providing example tools and resources"
        capabilities:
          tools: true
          resources: true
          prompts: true

# Web server configuration for SSE transport
server:
  port: 8082

logging:
  level:
    com.example.genericmcp: DEBUG
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai: DEBUG
    root: WARN