# =============================================
# Default Application Configuration for Generic MCP Server
# ---------------------------------------------
# Default configuration uses STDIO transport (most common use case).
# For SSE transport, use: --spring.profiles.active=sse
# =============================================

spring:
  application:
    name: generic-mcp-server
  main:
    banner-mode: off
    log-startup-info: false
  ai:
    mcp:
      server:
        enabled: true
        stdio: true  # Enable stdio transport for Claude Desktop
        name: generic-mcp-server
        version: 2.0.1
        type: SYNC
        instructions: "Generic MCP server providing example tools and resources via STDIO transport"
        capabilities:
          tools: true
          resources: true
          prompts: true

# Disable web server for default STDIO mode
server:
  port: -1

logging:
  level:
    com.example.genericmcp: DEBUG
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai: DEBUG
    root: WARN