spring:
  application:
    name: generic-mcp-server
  main:
    banner-mode: off
    log-startup-info: false
  ai:
    mcp:
      server:
        enabled: true
        # Stdio transport only for Claude Desktop compatibility
        capabilities:
          tools: true
          resources: true
          prompts: true

logging:
  level:
    com.example.genericmcp: DEBUG
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai: DEBUG
    root: WARN