# =============================================
# SSE Transport Configuration for Generic MCP Server
# ---------------------------------------------
# This profile configures the server for SSE (Server-Sent Events) transport only,
# suitable for web clients and HTTP-based integrations.
# 
# Usage: java -jar generic-mcp-server.jar --spring.profiles.active=sse
# Server will be available at: http://localhost:8082/mcp
# =============================================

spring:
  application:
    name: generic-mcp-server
  main:
    banner-mode: off
    log-startup-info: false
  ai:
    mcp:
      server:
        enabled: true
        stdio: false  # Disable STDIO transport for pure SSE mode
        name: generic-mcp-server
        version: 2.0.0
        type: SYNC
        instructions: "Generic MCP server providing example tools and resources via SSE transport"
        capabilities:
          tools: true
          resources: true
          prompts: true

# Web server configuration for SSE transport
server:
  port: 8082

logging:
  level:
    com.example.genericmcp: DEBUG
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai: DEBUG
    root: WARN