# =============================================
# STDIO Transport Configuration for Generic MCP Server
# ---------------------------------------------
# This profile configures the server for STDIO transport only,
# suitable for Claude Desktop and similar tools that use process pipes.
# 
# Usage: java -jar generic-mcp-server.jar --spring.profiles.active=stdio
# =============================================

spring:
  application:
    name: generic-mcp-server
  main:
    banner-mode: off
    log-startup-info: false
  ai:
    mcp:
      server:
        enabled: true
        stdio: true  # Enable STDIO transport for Claude Desktop
        name: generic-mcp-server
        version: 2.0.1
        type: SYNC
        instructions: "Generic MCP server providing example tools and resources via STDIO transport"
        capabilities:
          tools: true
          resources: true
          prompts: true

# Disable web server for pure STDIO mode
server:
  port: -1  # Disable web server

logging:
  level:
    com.example.genericmcp: DEBUG
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai: DEBUG
    root: WARN