server:
  port: 8081

spring:
  application:
    name: generic-mcp-server
  ai:
    mcp:
      server:
        enabled: true
        # WebMVC SSE transport is auto-configured by spring-ai-starter-mcp-server-webmvc
        endpoint: /mcp
        capabilities:
          tools: true
          resources: true
          prompts: true

logging:
  level:
    com.example.genericmcp: DEBUG
    org.springframework.ai.mcp: DEBUG